### ISSUE TITLE
Still Active?

### ISSUE THREAD

**Issue by JamesCoyle** [schmuli/atom-less#10]
Is development still active? There are quite a few packages to do this but they all seem to no longer be developed. While not the biggest, this one seems to be a little more active and I really like the idea of project wide settings. 99% of the time I have a css folder and a less folder that share the same structure so it would be nice to have one single hidden file in the project root that specifies files in the less folder should be compiled on save into files in the css folder.

**Comment by schmuli** [comment]
This project is active.

However, I am currently using the current feature set on an almost daily basis and it is working for me. Unfortunately, I don't have the time to develop new features, even though I think that they would be a great benefit, as you have pointed out yourself.

I am open to accepting PRs, but the truth is that if I were to work on this, I would start by refactoring everything to JavaScrip first.

**Comment by schmuli** [comment]
I'm sorry but the code hasn't been updated in a long time, since I am no longer using Atom, and therefore not maintaining the code anymore.

Sorry about that. I am willing to transfer ownership of the code and plugin to anyone who wants it.
