### ISSUE TITLE
Unrecognised input. Possibly missing something

### ISSUE THREAD

**Issue by thecosss** [schmuli/atom-less#16]
I guess when i reach something about 200 and more lines i get this alert on save. Why the hell is this happening?

**Comment by schmuli** [comment]
@thecosss I'm sorry but the code hasn't been updated in a long time, since I am no longer using Atom, and therefore not maintaining the code anymore.

Sorry about that. I am willing to transfer ownership of the code and plugin to anyone who wants it.
