### ISSUE TITLE
Atom crashes on save if less file is empty

### ISSUE THREAD

**Issue by davidchoy** [schmuli/atom-less#17]
Didn't happen before, but Atom 1.20.1 crashes when you:

a) create a new empty file in atom with a filename ending with the extension .less
b) save the file

If you add text to the file before saving, it still crashes and does not save the file.

A workaround is to initially add content to the file before saving. This can be done in several ways, including:

(a) Adding text and saving in a different program
(b) Disabling the plugin on first save
(c) Creating a new file without the less extension and then adding it by renaming it once it is no longer empty

(I'm using a Mac. Have not tested on my PC.)

**Comment by schmuli** [comment]
@davidchoy I'm sorry but the code hasn't been updated in a long time, since I am no longer using Atom, and therefore not maintaining the code anymore.

Sorry about that. I am willing to transfer ownership of the code and plugin to anyone who wants it.
