### ISSUE TITLE
Feature request: Include less-plugin-functions

### ISSUE THREAD

**Issue by jpeltoniemi** [schmuli/atom-less#2]
I added this plugin to my own version, but it's a crude patch and not done the right way at all. I would like to request that you consider including this plugin the proper way. I see it as a big improvement to otherwise limited LESS functionality.

https://github.com/seven-phases-max/less-plugin-functions

Alternatively, or maybe even preferably, if the compiler allows it, it would also be very cool to be able to include a js file containing custom functions. I think at least the browser version of LESS supports custom js functions.

**Comment by schmuli** [comment]
I'm sorry but the code hasn't been updated in a long time, since I am no longer using Atom, and therefore not maintaining the code anymore.

Sorry about that. I am willing to transfer ownership of the code and plugin to anyone who wants it.
