### ISSUE TITLE
Feature request: enable unsafe eval

### ISSUE THREAD

**Issue by jpeltoniemi** [schmuli/atom-less#3]
Atom doesn't allow eval (for a good reason). This makes it impossible to use javascript inside less files, which I admit isn't a problem for most, but would still be a very neat thing to have. Atom has its own loophole package (https://github.com/atom/loophole) that enables eval for a desired scope. I tried fiddling with it by myself, but since I'm still quite a novice with node and coffeescript, I couldn't make it work.

If it's as easy to implement as its readme suggests, I would appreciate its inclusion in atom-less greatly.

**Comment by schmuli** [comment]
I'm sorry but the code hasn't been updated in a long time, since I am no longer using Atom, and therefore not maintaining the code anymore.

Sorry about that. I am willing to transfer ownership of the code and plugin to anyone who wants it.
