### ISSUE TITLE
Example of correct settings syntax?

### ISSUE THREAD

**Issue by wallyfaye** [schmuli/atom-less#4]
Hi, I am trying to use this but don't understand the "valid less comment" on the first line.  none of the below work, can you please provide an example?  also, is it necessary for the main parameter to be declared (i thought it might be redundant since the file being saved would normally be the file that should be compiled)

// { "main": "styles.less", "out": "styles.min.css", "cleancss": "[ie8]" }
// '{ "main": "styles.less", "out": "styles.min.css", "cleancss": "[ie8]" }'
/\* '{ "main": "styles.less", "out": "styles.min.css", "cleancss": "[ie8]" }' */

**Comment by schmuli** [comment]
The comment on the first line must be valid JSON, but without the leading '{' or the trailing '}'. Your first example is correct, but just remove the curly brackets.

"main" and "out" are mutually exclusive; if they both appear, "main" will be ignored. "out" is used to specify the name of the CSS file that will be created. "main" is used to specify another LESS file that should be compiled when saving the current file.

Hope that helps you.

**Comment by ManuelColombo** [comment]
could you help me with the correct syntax for autoprefixer?

Thank you

**Comment by schmuli** [comment]
Sure, although to be honest I haven't needed more than a simple config, so haven't tested all the valid options yet.

If the value resolves to a string, it is used as the value for the AutoPrefixer <code>browser</code> config property for specifying which versions of browsers to provide support for.

If the value resolves to an object, the value will be passed 'as-is' to the AutoPrefixer plugin.

For example, the simplest configuration is:

```
// "main": "styles.css", "autoprefixer": "last 2 versions"
```

Please see the [AutoPrefixer readme](https://github.com/postcss/autoprefixer) for the valid configuration properties and values.

**Comment by ponychicken** [comment]
Hm, for me it doesn't do anything. No error, no output..

**Comment by schmuli** [comment]
My mistake, sorry.
Instead of "main", please use " out".
"main" has a different purpose.

**Comment by kingma-sbw** [comment]
// { "main": "style.less", "out": "../style.css", "sourcemap": "true"}

Not sure what is wrong with this json comment in the first line, but atom-less refuses to compile
